// Angular/src/app/game/game/game.component.ts
import { Component, OnInit } from '@angular/core';

import { ActivatedRoute } from '@angular/router';
import { StateService, State } from './../state.service';

@Component({
  selector: 'app-game',
  templateUrl: './game.component.html',
  styleUrls: ['./game.component.css']
})
export class GameComponent implements OnInit {

  constructor(route: ActivatedRoute, stateService: StateService) {
  	if (route.snapshot.data.continue) {
  		stateService.state = {
			  "turn": "PLAYER0",
			  "values": [
			    [ "X", "X", "-"],
			    [ "X","0","-"],
			    ["0","-","-"]
			  ]
			};
  	} else {
  		stateService.reset();
  	}
  }

  ngOnInit() {
  }

}

<div *ngIf="_status == 'fetching'">Loading...</div>

<div *ngIf="_status == 'success'">

	<form *ngIf="(_stateService.state$ | async).player_name == ''">
		<label>Introduce Player Name</label>
		<input [(ngModel)]="_player_name" type="text" name="_player_name">
		<input (click)="_handleSubmitClick()" type="submit" value="Submit">
	</form>

	<div *ngIf="(_stateService.state$ | async).player_name != ''">
		<app-header></app-header>
		<app-board></app-board>
	</div>
	
</div>

<h3 *ngIf="_status !== 'success' && _status !== 'fetching'">Error getting state from server. The error was: {{ _status }}</h3>

// react-ttt/src/components/Tictactoe/Game.jsx
import React from 'react';
import Header from './Header.jsx';
import Board from './Board.jsx';
import { connect } from 'react-redux';
import { playPosition, fetchState, newPlayer } from './../../reducers/actions';

class Game extends React.Component {
  constructor(props) {
    super(props);
    this.state = {player_name: ""};
    this.appClick = this.appClick.bind(this);
    this.handlePlayerInputChange = this.handlePlayerInputChange.bind(this);
    this.handlePlayerSubmit = this.handlePlayerSubmit.bind(this);
  }
  appClick(rowNumber, columnNumber) {
      this.props.dispatch(playPosition(rowNumber, columnNumber, this.props.turn, this.props.values));
  }
  handlePlayerInputChange(event){
    this.setState({player_name: event.target.value});
  }
  handlePlayerSubmit(event) {
    console.log('A name was submitted: ' + this.state.player_name);
    event.preventDefault();
    this.props.dispatch(newPlayer(this.state.player_name));
  }
  componentDidMount(){
    console.log("componentDidMount");
    if(this.props.continue===true){
      this.props.dispatch(fetchState());
    }
  }
  render() {
    if(this.props.fetch.fetching){
      return <div className="loader"></div>;
    } else if(this.props.fetch.fetching===false && this.props.fetch.error){
      console.log(this.props.fetch.error);
      return <h3>Error getting state from server. The error was: {this.props.fetch.error.toString()}</h3>;
    }else{
      if(this.props.player_name!==""){
          let welcome_text = "Welcome " + this.props.player_name;
          let text = "Turn of " + this.props.turn;
          return (
            <div>
              <Header text={text} welcome_text={welcome_text}/>
              <Board values={this.props.values}  appClick={this.appClick} />
            </div>
          );
      } else {
          return (<header className="header">
            <form onSubmit={this.handlePlayerSubmit}>
              <label>
                Introduce Player Name:
                <input type="text" value={this.state.player_name} onChange={this.handlePlayerInputChange} />
                <input type="submit" value="Submit" />
              </label>
            </form>
          </header>
        );
      }
    }
  }
}

function mapStateToProps(state) {
    return {
        values: state.values,
        turn: state.turn,
        fetch: state.fetch,
        player_name: state.player_name
    };
}
export default connect(mapStateToProps)(Game);
